### PR TITLE
P100.handshake() starts new TCP session

### LINKED ISSUE #50: ToFix: payload assumption
I'll probably create a PR for this shortly.
I get this randomly off a plug

Not sure if this was a design decision, to put the decrypt outside the try statement?

https://github.com/fishbigger/TapoP100/blob/2d3478927928a3c2bec31e730fea150c0d52245b/PyP100/PyP100.py#L156

```
INFO:root:Traceback (most recent call last):
  File "./plugcontroller.py", line 51, in plug_turn_off
    p100.login()
  File "/usr/local/lib/python3.7/dist-packages/PyP100/PyP100.py", line 156, in login
    decryptedResponse = self.tpLinkCipher.decrypt(r.json()["result"]["response"])
KeyError: 'result'
```

### PR DESCRIPTION
**Pull request by realzoulou**
Fix #50, #54, #62, #64.
Description:
P100 instance initially has no open requests.Session.
When P100.handshake() is called, a previous Session is closed and a new one created.
Behavioral change: P100.getDeviceName() now expects that handshake() and login() has happened on the P100 instance before.

Signed-off-by: richi <zoulourns@gmail.com>

### CODE REVIEW

**Comment by realzoulou** [comment]
Tested with P110 devices only, but my own HA integration covers these P100 APIs:
handshake, login, getDeviceInfo, getDeviceName

**Comment by realzoulou** [comment]
@fishbigger Have you decided which PR to take? #65 or #66 ?

**Comment by realzoulou** [comment]
Resolved merge conflicts

**Comment by fishbigger** [comment]
Sorry I didn't get to this sooner. It seems a lot better than my quick fix earlier.

**Pull request merged**
